"""empty message

Revision ID: 62fe64155ef9
Revises: e0a11cf585cc
Create Date: 2023-07-04 13:19:46.383970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fe64155ef9'
down_revision = 'e0a11cf585cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('project_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('jobs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jobs_user_id_fkey', 'users', ['user_id'], ['id'])

    op.drop_table('projects')
    # ### end Alembic commands ###
